name: Shared Checks

on:
  workflow_call:

permissions:
  contents: read

env:
  COLUMNS: 150

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.8.19

      - name: Install dependencies
        run: uv sync --frozen --group dev --python 3.10

      - name: Run ruff check
        run: uv run ruff check .

      - name: Run ruff format check
        run: uv run ruff format --check .

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.8.19

      - name: Install the project
        run: uv sync --frozen --group dev --python ${{ matrix.python-version }}

      - name: Run pytest
        run: uv run pytest tests/ --tb=short

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.8.19

      - name: Install dependencies
        run: uv sync --frozen --group dev --python 3.12

      - name: Run tests with coverage
        run: uv run pytest tests/ --cov=src/memcord --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false